# Generated by Django 5.2.12 on 2026-09-07 14:07

import myaut.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaut', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=myaut.models.user_avatar_directory_path, verbose_name='Аватар'),
        ),
    ]
